Kruptorg/Kruptorg/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg.views import get_schema_view
from django.conf import settings
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title = 'Kruptorg api',
        default_version = 'v1',
        description = 'Документация для сайта',
    ),
    permission_classes = (permissions.AllowAny, ),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('v1/', include("api.urls")),
    path('', include("diplom.urls"))
]

urlpatterns += [
    re_path(r'^swagger(?P<format>.json|.yaml)$',
       schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
       name='schema-swagger-ui'),
]

handler404 = 'diplom.views.page_not_found'

handler500 = 'diplom.views.server_error'

handler403 = 'diplom.views.csrf_failure'

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debugtoolbar:
    urlpatterns += (path('__debug/', include(debug_toolbar.urls)),)

Kruptorg/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import AddOrderView, AddOrderListView

v1_router = DefaultRouter()
v1_router.register('AddOrder', AddOrderView, basename='AddOrder')
v1_router.register('AddOrderList', AddOrderListView, basename='AddOrderList')
# v1_router.register('token/create', TokenCreationView, basename='TokenCreation')

urlpatterns = [
    path('', include(v1_router.urls))
]

Kruptorg/diplom/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import IndexListView, login_view, logout_view, ArchiveListView, change_status, send_comment

app_name = 'diplom'

urlpatterns = [
    path('', IndexListView.as_view(), name='main_page',),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('archive/', ArchiveListView.as_view(), name='archive'),
    path('change_status/', change_status, name='change_status'),
    path('send_comment/', send_comment, name='send_comment')
]

Kruptorg/templates/includes/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Kruptorg/templates/includes/header.html
{% load static %}
{% block content %}
<style>header{
            background: #63EA99;
            }
</style>
<style>button{
            background-color: transparent;
            border: none;
            }
</style>
<style>a{
           text-decoration: none;
            }
</style>
<div class="container-fluid p-0 m-0" style="box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.5)">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'diplom:main_page' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none" style="margin-left: 80px">
            <img src="{% static 'img/agromaster_logo.png' %}" width="124" height="60" class="m-2">
        </a>
     <ul class="nav nav-pills">
         <li>
             <button style="border: 2px solid #FFFFFF; box-shadow: 4px 4px 4px 0px rgba(0, 0, 0, 0.45);" class="btn btn-outline-secondary d-inline-flex align-items-center m-1">
                 <a class="text-white" href="{% url 'diplom:archive' %}">Архив  <img src="{% static 'img/archive.png' %}" width="24" height="24"></a>
             </button>
         </li>
         <li>
             <img src="{% static 'img/icon.png' %}" width="50" height="50">
         </li>
         <li>
             <button style="border: 2px solid #FFFFFF; box-shadow: 4px 4px 4px 0px rgba(0, 0, 0, 0.45);" class="btn btn-outline-secondary d-inline-flex align-items-center m-1">
                 <a class="text-white" href="{% url 'diplom:logout' %}">Выйти  <img src="{% static 'img/logout.png' %}" width="24" height="24"></a>
             </button>
         </li>
     </ul>
    </header>
</div>
{% endblock %}

Kruptorg/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}