Kruptorg/Kruptorg/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from drf_yasg.views import get_schema_view
from django.conf import settings
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title = 'Kruptorg api',
        default_version = 'v1',
        description = 'Документация для сайта',
    ),
    permission_classes = (permissions.AllowAny, ),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('v1/', include("api.urls")),
    path('', include("diplom.urls"))
]

urlpatterns += [
    re_path(r'^swagger(?P<format>.json|.yaml)$',
       schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0),
       name='schema-swagger-ui'),
]

handler404 = 'diplom.views.page_not_found'

handler500 = 'diplom.views.server_error'

handler403 = 'diplom.views.csrf_failure'

if settings.DEBUG:
    import debug_toolbar
    # Добавить к списку urlpatterns список адресов из приложения debugtoolbar:
    urlpatterns += (path('__debug/', include(debug_toolbar.urls)),)

Kruptorg/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import AddOrderView, AddOrderListView

v1_router = DefaultRouter()
v1_router.register('AddOrder', AddOrderView, basename='AddOrder')
v1_router.register('AddOrderList', AddOrderListView, basename='AddOrderList')
# v1_router.register('token/create', TokenCreationView, basename='TokenCreation')

urlpatterns = [
    path('', include(v1_router.urls))
]

Kruptorg/diplom/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import IndexListView, login_view, logout_view, ArchiveListView, change_status, send_comment

app_name = 'diplom'

urlpatterns = [
    path('', IndexListView.as_view(), name='main_page',),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('archive/', ArchiveListView.as_view(), name='archive'),
    path('change_status/', change_status, name='change_status'),
    path('send_comment/', send_comment, name='send_comment')
]

Kruptorg/templates/pages/403_csrf.html
{% extends "base.html" %}
{% block title %} Ошибка 403 - отсутствие прав {% endblock %}
{% block content %}
<h1>Ошибка 403 - отсутствие прав</h1>
{% endblock %}

Kruptorg/templates/pages/archive.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Kruptorg/templates/pages/index.html
{% extends "base.html" %}
{% load static %}
{{request.path}}
{% block title %}Заказы{% endblock %}
{% block content %}
<div class="container-fluid p-4" style="max-width:85%">
    {% if request.resolver_match.url_name == 'main_page' %}
    <ul class="nav justify-content-end" style="margin-bottom:20px">
    <li class="nav-item">
        <div class="col m-1">К отгрузке сегодня: {{today_orders_count}}</div>
    </li>
    <li class="nav-item">
        <div class="col m-1">Измененные заказы: {{changes_order_count}}</div>
    </li>
    </ul>
    {% endif %}
    <div class="row align-items-start">
        <div class="col"><b>№ Заказа</b>
            <button type="button" class="btn d-inline-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false" >
                <img src="{% static 'img/filter.png' %}" width="20" height="18">
            </button>
        <div data-bs-theme="light" class="dropdown-menu">
        <form class="p-2 mb-2 bg-body-tertiary border-bottom">
            <div class="d-flex align-items-center">
               <input type="search" class="form-control" autocomplete="false" placeholder="поиск">
                <img src="{% static 'img/search.png' %}" width="24" height="24">
            </div>
        </form>
        <ul class="list-unstyled mb-0">
            <li>
                <a class="dropdown-item d-flex align-items-center gap-2 py-2">Сортировать
            <img src="{% static 'img/a-z.png' %}" width="24" height="24">
            </a></li>
            <li><a class="dropdown-item d-flex align-items-center gap-2 py-2">Сортировать
            <img src="{% static 'img/z-a.png' %}" width="24" height="24">
            </a></li>
        </ul>
        </div>
        </div>
        <div class="col"><b>Дата отгрузки</b>
            <button type="button" class="btn d-inline-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{% static 'img/filter.png' %}" width="20" height="18">
            </button>
        <div data-bs-theme="light" class="dropdown-menu">
         <form class="p-2 mb-2 bg-body-tertiary border-bottom">
             <div class="d-flex align-items-center">
                <input type="search" class="form-control" autocomplete="false" placeholder="поиск">
                 <img src="{% static 'img/search.png' %}" width="24" height="24">
             </div>
        </form>
        <ul class="list-unstyled mb-0">
            <li><a class="dropdown-item d-flex align-items-center gap-2 py-2" href="?order=date">Сортировать
            <img src="{% static 'img/a-z.png' %}" width="24" height="24">
            </a></li>
            <li><a class="dropdown-item d-flex align-items-center gap-2 py-2" href="?order=-date">Сортировать
            <img src="{% static 'img/z-a.png' %}" width="24" height="24">
            </a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item d-flex align-items-center gap-2 py-2">Сегодня</a></li>
            <li><a class="dropdown-item d-flex align-items-center gap-2 py-2">Завтра</a></li>
        </ul>
    </div>
    </div>
    <div class="col"><b>Статус</b>
        <button type="button" class="btn d-inline-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/filter.png' %}" width="20" height="18">
        </button>
        <div data-bs-theme="light" class="dropdown-menu m-1 p-1">
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked0">
            <label class="form-check-label" for="flexCheckChecked1">Поступил</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked1">
            <label class="form-check-label" for="flexCheckChecked1">Принят</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked2">
            <label class="form-check-label" for="flexCheckChecked2">В сборке</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked3">
            <label class="form-check-label" for="flexCheckChecked3">Ожидает отгрузки</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked4">
            <label class="form-check-label" for="flexCheckChecked4">Отгружается</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked5">
            <label class="form-check-label" for="flexCheckChecked5">Возникла проблема</label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked6">
            <label class="form-check-label" for="flexCheckChecked6">Изменен</label>
        </div>

    </div>
    </div>

    <div class="col"><b>Номер машины</b>
        <button type="button" class="btn d-inline-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{% static 'img/filter.png' %}" width="20" height="18">
        </button>
    <div data-bs-theme="light" class="dropdown-menu">
        <form class="p-2 mb-2 bg-body-tertiary border-bottom">
            <div class="d-flex align-items-center">
            <input type="search" class="form-control" autocomplete="false" placeholder="поиск">
            <img src="{% static 'img/search.png' %}" width="24" height="24">
            </div>
        </form>
    </div>
    </div>
    <div class="col"><b>Номер прицепа</b></div>
    <div class="col"><b>Всего мест</b></div>
    <div class="col"><b>Всего наименований</b></div>
    </div>

<hr style="border: 1px solid black">


{% for order_item in orders %}
<div class="card" style="background: {% if order_item.status == 'Изменен' or order_item.status == 'Возникла проблема'%} #F3928C {% else %} #9EFEC3 {% endif %};
                        margin-bottom:20px; box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.5); border: 2px solid {% if order_item.status == 'Изменен' or order_item.status == 'Возникла проблема'%} #C23522 {% else %} #157014 {% endif %};">
    <button type="button" class="btn d-inline-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false" id="comment_form">
        <img src="{% static 'img/comment_img.svg' %}" style="position: absolute; top: 0; right: 0; width: 25px; height:25px; margin-right:3px; margin-top:3px;">
    </button>
    <ul data-bs-theme="light" class="dropdown-menu m-1 p-1" aria-labelledby="comment_form" style="width: 100%;">
        {% for comment in order_item.comment.all %}
        <div>
            <strong>{{ comment.author.username }}</strong>
            <p>{{ comment.text }}</p>
            <small>{{ comment.created_at }}</small>
        </div>
        {% endfor %}
        <form method="post" action="{% url 'diplom:send_comment' %}">
            {% csrf_token %}
            <textarea name="comment" class="form-control" placeholder="Оставьте комментарий..."></textarea>
            <input type="hidden" name="order_number" value="{{ order_item.order_number }}">
            <button type="submit" class="btn btn-primary mt-2">Отправить</button>
        </form>
    </ul>
        <div class="card-body m-1" >
        <div class="row align-items-start">
            <div class="col">
                № {{order_item.order_number}}
            </div>
            <div class="col">
                {{order_item.date}}
            </div>
            <div class="col">
                {{order_item.status}}
                {% if isstorekeeper %}
                <form method="post" action="{% url 'diplom:change_status' %}">
                    {% csrf_token %}
                    <input type="hidden" name="order_number" value="{{ order_item.order_number }}">
                    <button type="button" class="btn d-inline-flex align-items-center" data-bs-toggle="dropdown" aria-expanded="false" id="status_dropdown">
                       <img src="{% static 'img/change_status.png' %}" width="24" height="24">
                   </button>
                    <ul data-bs-theme="light" class="dropdown-menu m-1 p-1" aria-labelledby="status_dropdown">
                      <li>
                          <button class="dropdown-item" type="submit" name="status" value="Принят">
                              Принят
                          </button>
                      </li>
                      <li>
                          <button class="dropdown-item" type="submit" name="status" value="В сборке">
                              В сборке
                          </button>
                      </li>
                      <li>
                          <button class="dropdown-item" type="submit" name="status" value="Ожидает отгрузки">
                              Ожидает отгрузки
                          </button>
                      </li>
                      <li>
                          <button class="dropdown-item" type="submit" name="status" value="Отгружается">
                              Отгружается
                          </button>
                      </li>
<!--                      <li>-->
<!--                          <button class="dropdown-item" type="submit" name="status" value="Возникла проблема">-->
<!--                              Возникла проблема-->
<!--                          </button>-->
<!--                      </li>-->
<!--                      <li>-->
<!--                          <button class="dropdown-item" type="submit" name="status" value="Изменен">-->
<!--                              Изменен-->
<!--                          </button>-->
<!--                      </li>-->
                    </ul>
                </form>
                {% endif %}
            </div>
            <div class="col">
                {{order_item.car_number}}
            </div>
            <div class="col">
                {{order_item.trailer_number}}
            </div>
            <div class="col">
                {{order_item.places}}
            </div>
            <div class="col">
                {{order_item.names}}
                <button type="button" data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapseTable{{forloop.counter}}" data-bs-target="#collapseTable{{forloop.counter}}">
                   <img src="{% static 'img/dropdown_table.png' %}" width="20" height="8">
               </button>
            </div>
        </div>
    </div>
</div>
<table class="table table-hover collapse" id="collapseTable{{forloop.counter}}"
       style="text-align: center;border-collapse: collapse; border: 1px solid #000000; background-color: #F0FBF4">
    <thead>
    <tr>
        <th>№</th>
        <th>Наименование товара</th>
        <th>Масса НЕТТО</th>
        <th>Количество</th>
        <th>Ед.изм</th>
        <th>Кол-во мест</th>
        <th>Шт/место</th>
    </tr>
    </thead>
    {% for list_item in order_item.items.all %}
    <tbody  >
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{list_item.name}}</td>
            <td>{{list_item.mass}}</td>
            <td>{{list_item.count}}</td>
            <td>{{list_item.unit}}</td>
            <td>{{list_item.place}}</td>
            <td>{{list_item.unit_place}}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endfor %}

</div>



<!--{% for order_card in order_cards %}-->
<!--<article class="mb-5">-->
<!--{% include 'includes/order_card.html' %}-->
<!--</article>-->
<!--{% endfor %} d-block position-static pt-0 mx-0 rounded-3 shadow overflow-hidden w-280px-->
{% include 'includes/paginator.html' %}
{% endblock %}

Kruptorg/templates/pages/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="shortcut icon" href="{% static 'img/agromaster_logo.png' %}" type="image">
    <title>Страница авторизации</title>
    <style>body{
            background: linear-gradient(306.04deg, #63EA99 72.64%, rgba(215, 255, 231, 0) 112.22%);
            height: 100vh;
            margin: 0;
            background-repeat: no-repeat;
            background-attachment: fixed;
            }
    </style>
</head>
<body>
<main>
<div class="col d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card" style="width: 40rem;">
    <div class="card-header">
        ВХОД
    </div>
    <div class="card-body">
        <form method="post" action="{% url 'diplom:login' %}">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="hidden" name="next" value="{{ next }}">
            {% bootstrap_button button_type="submit" content="ВОЙТИ" %}
        </form>
    </div>
</div>
</div>
</main>
</body>
</html>